name: Config varibale Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:    

env:
  GLOBAL_ENV: "qa"

jobs:
  repository_var_job:    
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        #project_id -> repository variables
        #repository, triggering_actor -> context variables
        run: |
          echo "Hello..running project - ${{vars.project_id}} on env- $GLOBAL_ENV"
          echo "Repo name : ${{github.repository}}" 
          echo "Triggered by ${{github.triggering_actor}}"